<%@ page language='java' contentType='text/html; charset=ISO-8859-1' pageEncoding='ISO-8859-1'%>
<!-- HEAD -->
<%@include file='../../head.html' %>

<body>
    <!-- Main View -->
    <div class='container-fluid h-100'>
        <!-- Nav Bar -->
        <div class='row ten blue-container nav-main align-items-center p-2'>
            <div class='col-4 mt-1'>
                <h2>RepGraph</h2>
            </div>
            <div class='col-4 mx-auto'>
                <div class='d-flex justify-content-center'>
                    <h1>Analysis Tool</h1>
                </div>
            </div>
            <div class='col-4 mt-1'>
                <ul>
                    <li><a href='library'>
                            <h5>Graph Library</h5>
                        </a></li>
                </ul>
            </div>
        </div>
        <!-- Analysis View -->
        <div class='row ninety'>
            <!-- Left hand column-->
            <div class='col-3 h-100 pt-4'>
                <div class='container-fluid h-100'>
                    <div class='row h-100'>
                        <div class='col-md-12 box' style='overflow-y: scroll;'>
                            <!-- ANALYSIS TOOLS -->
                            <h4>Analysis Tools</h4>
                            <!-- Display Subgraph of a Graph -->
                            <div class='card z-depth-0 bordered' style='margin-top:10px'>
                                <div id='subgraph-header' class='card-header'>
                                    <h5 class='mb-0' style="float: left;">Subgraph Selection</h5>
                                    <div class="fa-question-circle"
                                        style="float: right; font-family: fontawesome !important;" data-toggle="tooltip"
                                        data-placement="top"
                                        title="While the graph is in 'Single Selection' mode - select a node and click the 'Display Subgraph' button.">
                                    </div>
                                </div>
                                <div class='card-body'>
                                    <h6>Display subgraph generated by the currently selected node.</h6>
                                    <a href='#' id='subgraphBtn' class='btn btn-outline-primary btn-block disabled'
                                        style='margin-top: 10px;'>Display Subgraph
                                    </a>
                                    <a href='#' id='clearSubgraphBtn' class='btn btn-outline-primary btn-block'
                                        style='margin-top: 10px; display: none;'>
                                        Clear
                                    </a>
                                </div>
                            </div>
                            <!-- Search for Subgraph Patterns -->
                            <div class='card z-depth-0 bordered' style='margin-top:10px'>
                                <div id='subgraphPattern-header' class='card-header'>
                                    <h5 class='mb-0' style="float: left;">Subgraph Pattern Search</h5>
                                    <div class="fa-question-circle"
                                        style="float: right; font-family: fontawesome !important;" data-toggle="tooltip"
                                        data-placement="top"
                                        title="After a subgraph has been selected via the 'Subgraph Selection' tool, simply click the 'Search' button.">
                                    </div>
                                </div>
                                <div class='card-body'>
                                    <h6>Search the library for graphs containing the same currently displayed subgraph.
                                    </h6>
                                    <a href='#' id='patternMatchingBtn'
                                        class='btn btn-outline-primary btn-block disabled' style='margin-top: 10px;'>
                                        Search
                                    </a>
                                </div>
                            </div>
                            <!-- Second use case of Subgraph Patterns -->
                            <div class='card z-depth-0 bordered' style='margin-top:10px'>
                                <div id='nodePattern-header' class='card-header accordion'>
                                    <h5 class='mb-0' style="float: left;">Search for Node Matches</h5>
                                    <div class="fa-question-circle"
                                        style="float: right; font-family: fontawesome !important;" data-toggle="tooltip"
                                        data-placement="top"
                                        title="Click the 'Select Nodes' button to enter 'Group Selection' mode. Select the a group of nodes and click the 'Compute Search' button.">
                                    </div>
                                </div>
                                <div class='card-body'>
                                    <h6>Search the library for graphs containing nodes identical to a group of selected
                                        ones.</h6>
                                    <a href='#' id='nodeMatchingBtn' class='btn btn-outline-primary btn-block'
                                        style='margin-top: 10px;'>
                                        Select Nodes
                                    </a>
                                    <a href='#' id='nodeSearchingBtn' class='btn btn-outline-primary btn-block'
                                        style='margin-top: 10px; display: none;'>
                                        Search
                                    </a>
                                </div>
                            </div>
                            <!-- Compare Graphs -->
                            <div class='card z-depth-0 bordered' style='margin-top:10px'>
                                <div id='compare-header' class='card-header'>
                                    <h5 class='mb-0' style="float: left;">Compare Graphs</h5>
                                    <div class="fa-question-circle"
                                        style="float: right; font-family: fontawesome !important;" data-toggle="tooltip"
                                        data-placement="top" title="Simply click the 'Select Graph' button.">
                                    </div>
                                </div>
                                <div class='card-body'>
                                    <h6>Compare currently selected graph with a different one.</h6>
                                    <a href="#" id='compareBtn' class='btn btn-outline-primary btn-block'
                                        style='margin-top: 10px;'>
                                        Select Graph
                                    </a>
                                </div>
                            </div>
                            <!-- Compute and Test Graph Properties -->
                            <div class='card z-depth-0 bordered' style='margin-top:10px'>
                                <div id='properties-header' class='card-header'>
                                    <h5 class='mb-0' style="float: left;">Graph Properties</h5>
                                    <div class="fa-question-circle"
                                        style="float: right; font-family: fontawesome !important;" data-toggle="tooltip"
                                        data-placement="top" title="Simply click the 'View Properties' button.">
                                    </div>
                                </div>
                                <div class='card-body'>
                                    <h6>Test selected graph for various graph properties.</h6>
                                    <a href="#" id='propertiesBtn' class='btn btn-outline-primary btn-block'
                                        style='margin-top: 10px;'>
                                        View Properties</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Right hand column -->
            <div class='col-9 h-100 pt-4'>
                <div class='container-fluid h-80 box'>
                    <div class='row'>
                        <div class='col-md-12'>
                            <h3 id="modeHeader" style="float: left;">Mode: Single Selection</h3>
                            <div class="fa-lg fa-question-circle"
                                style="margin-left: 10px; margin-top: 10px; float: right; font-family: fontawesome !important;"
                                data-toggle="tooltip" data-placement="top"
                                title="Click on a node in 'Single Selection' to view its span and other nodes with tokens in the same span.">
                            </div>
                            <div class="dropdown">
                                <button type="button" class="btn btn-outline-primary dropdown-toggle float-right"
                                    data-toggle="dropdown">
                                    Graph Options
                                </button>
                                <div class="dropdown-menu">
                                    <a id="btnReset" class="dropdown-item" href="#">Reset</a>
                                    <a id="downloadBtn" class="dropdown-item downloadBtn" href="#">Download Graph as
                                        PNG</a>
                                    <a id="downloadSVGBtn" class="dropdown-item downloadSVGBtn" href="#">Download Graph
                                        as SVG</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row h-100">
                        <div class='col-md-12'>
                            <div class='graphContainer h-75' id='graphDisplay'>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Modals -->
    <div class='modal' id='propertiesModal' tabindex='-1' role='dialog' aria-hidden='true'>
        <div class='modal-dialog modal-dialog-centered' style='width: 70%; max-width: 90%;' role='document'>
            <div class='modal-content'>
                <div class='modal-header'>
                    <h5 class='modal-title' id='exampleModalLongTitle'>Properties Modal</h5>
                    <button type='button' class='close closePropertiesModalBtn' aria-label='Close'>
                        <span aria-hidden='true'>&times;</span>
                    </button>
                </div>
                <div class='modal-body' style='min-height: 550px;'>
                    <div class='row'>
                        <div class='col-12'>
                            <div id='propertiesModalGraph' class='longestPathGraph'
                                style='height: 250px; margin: auto;'>
                            </div>
                        </div>
                    </div>
                    <div class='row mt-3'>
                        <div class='col-4'>
                            <h5>View Basic Graph Properties</h5>
                            <hr>
                            <div><button id='displaySurfaceNodes' class='btn btn-secondary'
                                    style='margin-bottom: 10px;'>Show Surface Nodes</button>
                                <button id='displayAbstractNodes' class='btn btn-secondary'
                                    style='margin-bottom: 10px;'>Show Abstract Nodes</button></div>
                            <div><button id='displayTopNode' class='btn btn-secondary' style='margin-bottom: 10px;'>Show
                                    Top Node</button>
                                <button id='displayTokens' class='btn btn-secondary' style='margin-bottom: 10px;'>Show
                                    Tokens</button></div>
                        </div>
                        <div class='col-8'>
                            <h5>View Advanced Graph Properties</h5>
                            <hr>
                            <div class="row">
                                <div class="col-6">
                                    <h6>Planarity</h6>
                                    <p>${isPlanar}</p>
                                </div>
                                <div class="col-6">
                                    <h6>Connectivity</h6>
                                    <p>${weaklyConnected}</p>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-12">
                                    <div>
                                        <h6>Longest Path</h6><span>
                                            <p>Longest path consists of ${longestPath} connections.</p>
                                        </span>
                                    </div>
                                    <hr>
                                    <button id='displayLongestPath' class='btn btn-secondary'
                                        style='float: left; margin-right: 10px;'>Show
                                        Longest Path</button>
                                    <button id='displayCutVertices' class='btn btn-secondary' style="float: left;">Show
                                        Cut Vertices</button>
                                    <div class="fa-lg fa-question-circle"
                                        style="margin-left: 10px; margin-top: 10px; float: left; font-family: fontawesome !important;"
                                        data-toggle="tooltip" data-placement="top"
                                        title="Click a cut vertice in order to temporarily remove it from the graph.">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class='modal-footer'>
                    <div><button id='resetBtn' class='btn btn-secondary'>Reset to Default</button></div>
                    <a href='#' class='btn btn-secondary downloadBtn'>
                        Download Graph as PNG
                    </a>
                    <a href='#' class='btn btn-secondary downloadSVGBtn'>
                        Download Graph as SVG
                    </a>
                    <button type='button' class='btn btn-secondary closePropertiesModalBtn'>Close</button>
                </div>
            </div>
        </div>
    </div>
    <div class='modal' id='comparisonModal' tabindex='-1' role='dialog' aria-hidden='true'>
        <div class='modal-dialog pt-5' style='width: 90%; max-width: 90%;' role='document'>
            <div class='modal-content'>
                <div class='modal-header'>
                    <h5 class='modal-title'>Comparison Modal</h5>
                    <button type='button' class='close closeComparisonModalBtn' aria-label='Close'>
                        <span aria-hidden='true'>&times;</span>
                    </button>
                </div>
                <div class='modal-body'>
                    <div class='row'>
                        <div class='col-5'>
                            <!-- Table -->
                            <div class='tableWrapper'>
                                <table id='myTable' class='table table-hover table-sm'>
                                    <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Sentence</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                        <div class='col-7'>
                            <!-- Graph Display -->
                            <div class='row h-75'>
                                <div class='col-md-12'>
                                    <div class='graphContainer h-100' id='modalGraphDisplay'>
                                    </div>
                                </div>
                            </div>
                            <!-- Tokens -->
                            <div class='row fixed'>
                                <div class='container p-10' id='tokens'></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class='modal-footer'>
                    <a href='#' class='btn btn-secondary downloadBtn'>
                        Download Graph as PNG
                    </a>
                    <a href='#' class='btn btn-secondary downloadSVGBtn' style='margin-right: 10px;'>
                        Download Graph as SVG
                    </a>
                    <button type='button' class='btn btn-secondary closeComparisonModalBtn'>Close</button>

                </div>
            </div>
        </div>
    </div>
    <div class='modal' id='compareViewModal' tabindex='-1' role='dialog' aria-hidden='true'>
        <div class='modal-dialog pt-5' style='width: 90%; max-width: 90%;' role='document'>
            <div class='modal-content'>
                <div class='modal-header'>
                    <h5 class='modal-title'>Comparison View</h5>
                    <button type='button' class='close compareViewCloseBtn' aria-label='Close'>
                        <span aria-hidden='true'>&times;</span>
                    </button>
                </div>
                <div class='modal-body' style='min-height: 500px;'>
                    <div class='row'>
                        <div class='col-6'>
                            <div class='row mb-3 ml-3'>
                                <div class="col-12 text-center">
                                    <h6>Original Graph</h6>
                                </div>
                                <hr>
                            </div>
                            <div id='thisGraphDisplay' style='margin: auto; height: 400px; width: 95%;'></div>
                        </div>
                        <div class='col-6'>
                            <div class='row mb-3 ml-3'>
                                <div class="col-12 text-center">
                                    <h6>Selected Graph</h6>
                                </div>
                                <hr>
                            </div>
                            <div id='selectedGraphDisplay' style='margin: auto; height: 400px; width: 95%;'></div>
                        </div>
                    </div>
                </div>
                <div class='modal-footer'>
                    <a href='#' class='btn btn-secondary downloadBtn'>
                        Download Selected Graph as PNG
                    </a>
                    <a href='#' class='btn btn-secondary downloadSVGBtn' style='margin-right: 10px;'>
                        Download Selected Graph as SVG
                    </a>
                    <button id='key' class='btn btn-secondary' data-toggle='modal' data-target='#keyModal'>View
                        Key</button>
                    <button type='button' class='btn btn-secondary compareViewCloseBtn'>Close</button>
                </div>
            </div>
        </div>
    </div>
    <div class='modal' id='keyModal' tabindex='-1' role='dialog' aria-hidden='true'>
        <div class='modal-dialog modal-dialog-centered pt-5' style='width: 300px' role='document'>
            <div class='modal-content'>
                <div class='modal-header'>
                    <h5 class='modal-title' id='exampleModalLongTitle'>Key</h5>
                    <button type='button' class='close closeKeyModalBtn' aria-label='Close'>
                        <span aria-hidden='true'>&times;</span>
                    </button>
                </div>
                <div class='modal-body' style='min-height: 150px;'>
                    <div>
                        <span id='_labelMatch' class='dot'></span>
                        <span>Label Match</span>
                    </div>
                    <div>
                        <span id='_spanMatch' class='dot'></span>
                        <span>Span Match</span>
                    </div>
                    <div>
                        <span id='_labelSpanMatch' class='dot'></span>
                        <span>Label and Span Match</span>
                    </div>
                    <div>
                        <span id='_noMatch' class='dot'></span>
                        <span>No Match</span>
                    </div>
                </div>
                <div class='modal-footer'>
                    <button type='button' class='btn btn-secondary closeKeyModalBtn'>Close</button>
                </div>
            </div>
        </div>
    </div>
</body>
<script>
    $(document).ready(function () { //see above for why the JS is ALWAYS wapped.
        /* Variables */
        var showSubgraph = true; // boolean used to detect if subgraph or subgraph patterns should be shown when graph selected
        var whichSigma = 's'; // variable keeps track of which sigma instance is currently in use

        // Displays Graph on Load
        displayGraph();
        selectNode(); // allows you to interact with graph on load

        // Adds Data Table
        var table = $('#myTable').DataTable({
            ajax: {
                url: '/library/browse',
                type: 'GET',
                dataSrc: ''
            },
            columns: [
                { data: 'id' },
                { data: 'input' }
            ],
            scrollY: '50vh',
            scrollCollapse: false,
            pagingType: 'full_numbers',
        });


        var selectedId = '';
        // Click event for clicking on an item in the data table.
        $('#myTable tbody').on('click', 'tr', function () {
            if (showSubgraph) {
                analysisType = 'subgraph'; // show graph on right side
            }
            else {
                analysisType = 'graphComparison'; // open new modal for graph
            }
            var data = table.row(this).data();
            selectedId = data.id;
            $('#btnSelectGraph').removeAttr('disabled');
            var link = '/analysis/getVisualization/' + analysisType + '?graphId=' + selectedId;
            $.ajax({
                url: link,
                type: 'GET',
                success: function (result) {
                    // Opening new modal for comparison graph
                    if (analysisType == 'graphComparison') {
                        $('#compareViewModal').modal('show');
                        $('#comparisonModal').modal('hide');
                        $('#selectedGraphDisplay').empty();
                        destroyCompareGraph();
                        createAnalysisGraph(result, 'selectedGraphDisplay');

                        var link = '/analysis/getVisualization/' + 'graphCompareOriginal';
                        $.ajax({
                            url: link,
                            type: 'GET',
                            success: function (result) {
                                $('#thisGraphDisplay').empty();
                                destroyModalGraph();
                                createAnalysisGraph(result, 'thisGraphDisplay');
                                whichSigma = 'compareGraph';
                            }
                        });
                    }
                    // Showing pattern matches on the right hand side
                    else {
                        $('#modalGraphDisplay').empty();
                        destroyModalGraph();
                        createAnalysisGraph(result, 'modalGraphDisplay');
                    }
                }
            });
        });

        // Click event for RESET GRAPH button
        $('#btnReset').off('click').on('click', function () {
            displayGraph(); // Reset Graph
            // Reset Tools
            resetAll();
        });

        // Download graph as PNG
        $('.downloadBtn').off('click').on('click', function () {
            if (whichSigma == 's') {
                downloadGraphPNG('s');
            }
            if (whichSigma == 'modalGraph') {
                downloadGraphPNG('modalGraph');
            }
            if (whichSigma == 'compareGraph') {
                downloadGraphPNG('compareGraph');
            }
        });

        // Download graph as SVG
        $('.downloadSVGBtn').off('click').on('click', function () {
            if (whichSigma == 's') {
                downloadGraphSVG('s');
            }
            if (whichSigma == 'modalGraph') {
                downloadGraphSVG('modalGraph');
            }
            if (whichSigma == 'compareGraph') {
                downloadGraphSVG('compareGraph');
            }
        });

        // Click event for DISPLAY SUBGRAPH OF SELECTED NODE button
        $('#subgraphBtn').off('click').on('click', function () {
            $('#subgraph-header').css({ 'background-color': 'cornflowerblue', 'color': 'white' });
            $('#subgraphPattern-header').removeAttr('style');
            $('#nodePattern-header').removeAttr('style');
            $('#compare-header').removeAttr('style');
            $('#properties-header').removeAttr('style');
            console.log(selectedNode);
            if (!subgraphBtnSelected) {
                if (!selectedNode.startsWith('t')) {
                    var link = '/analysis/getSubgraphViz/' + selectedNode;
                    $.ajax({
                        url: link,
                        type: 'GET',
                        success: function (result) {
                            $('#graphDisplay').empty();
                            destroyAnalysisGraph();
                            createAnalysisGraph(result, 'graphDisplay');
                            $('#modeHeader').html("Mode: Subgraph Visualization");
                        }
                    });
                    s.refresh();
                }
                subgraphBtnSelected = true;

                $('#subgraphBtn').css('display', 'none');
                $('#clearSubgraphBtn').css('display', 'block');
                $('#patternMatchingBtn').removeClass('disabled');
            }
        });

        // Click event for CLEAR SUBGRAPH PATTERNS button
        $('#clearSubgraphBtn').off('click').on('click', function () {
            $('#clearSubgraphBtn').addClass('disabled');
            selectedNode = "";
            displayGraph();
        });

        // Click event for SEARCH FOR SUBGRAPH PATTERNS button
        $('#patternMatchingBtn').off('click').on('click', function () {
            $('#subgraphPattern-header').css({ 'background-color': 'cornflowerblue', 'color': 'white' });
            $('#subgraph-header').removeAttr('style');
            $('#nodePattern-header').removeAttr('style');
            $('#compare-header').removeAttr('style');
            $('#properties-header').removeAttr('style');
            $('#modalGraphDisplay').empty();
            console.log(selectedNode);
            if (selectedNode != '' || !selectedNode.startsWith('t')) {
                showSubgraph = true;
                var link = '/analysis/browseMatches/' + selectedNode;
                table.destroy();
                table = $('#myTable').DataTable({
                    ajax: {
                        url: link,
                        type: 'GET',
                        dataSrc: ''
                    },
                    columns: [
                        { data: 'id' },
                        { data: 'input' }
                    ],
                    scrollY: '40vh',
                    scrollCollapse: false,
                    pagingType: 'full_numbers'
                });
                $('#comparisonModal').modal('show');
                whichSigma = 'modalGraph';
            }
        });

        // Click event for SELECT A GROUP OF NODES button
        $('#nodeMatchingBtn').off('click').on('click', function () {
            displayGraph();
            resetAll();
            $('#nodePattern-header').css({ 'background-color': 'cornflowerblue', 'color': 'white' });
            $('#subgraph-header').removeAttr('style');
            $('#subgraphPattern-header').removeAttr('style');
            $('#compare-header').removeAttr('style');
            $('#properties-header').removeAttr('style');
            $('#subgraphBtn').addClass('disabled');
            $('#modeHeader').html('Mode: Group Selection');
            console.log('Selecting nodes...')
            selectNodeGroup();
        });

        // Click event for SEARCH FOR PATTERN OF SELECTED NODES button
        $('#nodeSearchingBtn').off('click').on('click', function () {
            $('#modalGraphDisplay').empty();
            if (nodeIds.length > 0) {
                $("*").addClass("disable-mouse");
                showSubgraph = true;
                var link = '/analysis/browseNodeMatches/' + nodeIds;
                table.destroy();
                table = $('#myTable').DataTable({
                    ajax: {
                        url: link,
                        type: 'GET',
                        dataSrc: ''
                    },
                    columns: [
                        { data: 'id' },
                        { data: 'input' }
                    ],
                    scrollY: '40vh',
                    scrollCollapse: false,
                    pagingType: 'full_numbers'
                });
                $('#comparisonModal').modal('show');
                whichSigma = 'modalGraph';
                $("*").removeClass("disable-mouse");
            }
            nodeIds = [];
            $('#nodeMatchingBtn').css('display', 'block');
            $('#nodeSearchingBtn').css('display', 'none');
        });

        // Click event for COMPARE TWO GRAPHS button
        $('#compareBtn').off('click').on('click', function () {
            $("*").addClass("disable-mouse");
            resetAll();
            $('#compare-header').css({ 'background-color': 'cornflowerblue', 'color': 'white' });
            $('#subgraph-header').removeAttr('style');
            $('#subgraphPattern-header').removeAttr('style');
            $('#nodePattern-header').removeAttr('style');
            $('#properties-header').removeAttr('style');
            $('#modalGraphDisplay').empty();
            // Create and Fill Data Table
            table.destroy();
            table = $('#myTable').DataTable({
                ajax: {
                    url: '/library/browse',
                    type: 'GET',
                    dataSrc: ''
                },
                columns: [
                    { data: 'id' },
                    { data: 'input' }
                ],
                scrollY: '40vh',
                scrollCollapse: false,
                pagingType: 'full_numbers'
            });
            showSubgraph = false;
            $('#comparisonModal').modal('show');
            $("*").removeClass("disable-mouse");
        })

        // Click event for CLOSE COMPARISON MODAL button
        $('.closeComparisonModalBtn').off('click').on('click', function () {
            $('#comparisonModal').modal('hide');
            $('#compare-header').removeAttr('style');
            $('#subgraphPattern-header').removeAttr('style');
            $('#nodePattern-header').removeAttr('style');
            showSubgraph = false;
            subgraphBtnSelected = false;
            displayGraph();
            selectNode();
            resetAll();
        });

        // Click event for CLOSE COMPARE VIEW MODAL button
        $('.compareViewCloseBtn').off('click').on('click', function () {
            $('#compareViewModal').modal('hide');
            $('#comparisonModal').modal('show');
        });

        // Click event for CLOSE KEY MODAL button
        $('.closeKeyModalBtn').off('click').on('click', function () {
            $('#keyModal').modal('hide');
            $('#compareViewModal').modal('show');
        });

        // Click event for COMPUTE AND TEST GRAPH PROPERTIES button
        $('#propertiesBtn').off('click').on('click', function () {
            $("*").addClass("disable-mouse");
            resetAll();
            $('#properties-header').css({ 'background-color': 'cornflowerblue', 'color': 'white' });
            $('#subgraph-header').removeAttr('style');
            $('#subgraphPattern-header').removeAttr('style');
            $('#nodePattern-header').removeAttr('style');
            $('#compare-header').removeAttr('style');
            var link = '/analysis/getVisualization/' + 'analysis';
            $.ajax({
                url: link,
                type: 'GET',
                success: function (result) {
                    $('#propertiesModalGraph').empty();
                    destroyModalGraph();
                    createAnalysisGraph(result, 'propertiesModalGraph');
                }
            });
            $('#propertiesModal').modal('show');
            whichSigma = 'modalGraph';
            $("*").removeClass("disable-mouse");
        });

        // Click event for DISPLAY LONGEST PATH button
        $('#displayLongestPath').off('click').on('click', function () {
            var link = '/analysis/getVisualization/' + 'longestPath';
            $.ajax({
                url: link,
                type: 'GET',
                success: function (result) {
                    $('#propertiesModalGraph').empty();
                    destroyModalGraph();
                    createAnalysisGraph(result, 'propertiesModalGraph');
                }
            });
        });

        // Click event for DISPLAY CUT VERTICES button
        $('#displayCutVertices').off('click').on('click', function () {
            var link = '/analysis/getVisualization/' + 'cutVertices';
            $.ajax({
                url: link,
                type: 'GET',
                success: function (result) {
                    $('#propertiesModalGraph').empty();
                    destroyModalGraph();
                    createAnalysisGraph(result, 'propertiesModalGraph');
                    showCutVertices();
                }
            });
        });

        // Click event for DISPLAY SURFACE NODES button
        $('#displaySurfaceNodes').off('click').on('click', function () {
            showSurfaceNodes();
        });

        // Click event for DISPLAY ABSTRACT NODES button
        $('#displayAbstractNodes').off('click').on('click', function () {
            showAbstractNodes();
        });

        // Click event for DISPLAY TOP NODE button
        $('#displayTopNode').off('click').on('click', function () {
            showTopNode();
        });

        // Click event for DISPLAY TOKENS button
        $('#displayTokens').off('click').on('click', function () {
            showTokens();
        });

        // Click event for CLOSE PROPERTIES MODAL button
        $('.closePropertiesModalBtn').off('click').on('click', function () {
            $('#propertiesModal').modal('hide');
            whichSigma = 's';
            $('#properties-header').removeAttr('style');
            displayGraph();
            selectNode();
            resetAll();
        });

        // Click event for PROPERTIES RESET BUTTON button
        $('#resetBtn').off('click').on('click', function () {
            var link = '/analysis/getVisualization/' + 'analysis';
            $.ajax({
                url: link,
                type: 'GET',
                success: function (result) {
                    $('#propertiesModalGraph').empty();
                    $('#modeHeader').html('Mode: Single Selection');
                    destroyModalGraph();
                    createAnalysisGraph(result, 'propertiesModalGraph');
                }
            });
        });

        $('#graphDisplay').on("click", function () {
            alert(nodeIds.length);
        });

        /**
         * Displays instance of sigma in main container on analysis page
         **/
        function displayGraph() {
            var analysisType = 'analysis';
            var link = '/analysis/getVisualization/' + analysisType;
            $.ajax({
                url: link,
                type: 'GET',
                success: function (result) {
                    $('#graphDisplay').empty();
                    destroyAnalysisGraph();
                    createAnalysisGraph(result, 'graphDisplay');
                }
            });
        };

        function resetAll() {
            // Reset Tools
            $("#modeHeader").html('Mode: Single Selection')
            // 1. Set all headers back to default
            $('#subgraph-header').removeAttr('style');
            $('#subgraphPattern-header').removeAttr('style');
            $('#nodePattern-header').removeAttr('style');
            $('#compare-header').removeAttr('style');
            $('#properties-header').removeAttr('style');

            // 2. Subgraph Selection
            selectedNode = "";
            subgraphBtnSelected = false;
            // show 'display' button
            $("#subgraphBtn").css('display', 'block');
            // 'display' button disabled
            $("#subgraphBtn").addClass("disabled");
            // hide 'clear' button
            $("#clearSubgraphBtn").css('display', 'none');

            // 3. Search for Subgraph Patterns
            // 'search' button disabled
            $("#patternMatchingBtn").addClass("disabled");

            // 4. Search for node matches
            nodeIds = [];
            // 'select nodes' button shown
            $('#nodeMatchingBtn').css('display', 'block');
            // 'search' button hidden
            $('#nodeSearchingBtn').css('display', 'none');
        }
    });
</script>